### ISSUE TITLE
Error pls. need your attention

### ISSUE THREAD

**Issue by SIN5ACOM** [cybernekit/scriptsCosmoSDK#1]
installed your script "restakingRizon.sh" all done step by step as like in your manual (i chooses tmux) now have continually following ERROR: 

BALANCE: 385201621 uatolo
Stake ALL
Error: The specified item could not be found in the keyring
Usage:
  rizond tx staking delegate [validator-addr] [amount] [flags] 

...how can be fixed this problem? Please need your help

**Comment by web3validator** [comment]
You should edit correctly your wallet name. Easy to show your keys name : rizond keys list
